### ISSUE TITLE
Decouple instance number from role in the logs

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/oni#152]
Maybe a Testground issue. Running https://github.com/filecoin-project/oni/pull/143 I was confused by the logs of different instances (2,3,4) when in fact not all instances had the same role. Instead of a generic `<< instance   n >>` where every role shares the same indexing I'd rather have different indexes for different roles, e.g., `<< miner   1 >>`, `<< miner   2 >>`, and `<< client   1 >>` (not `<< client   3 >>` or `<< instance   3 >>`). This may break the current log alignment, but then again, I probably don't want to have aligned logs from different roles.

**Comment by raulk** [comment]
Yeah, I've been tripping on this one very frequently too. We can't have Testground print roles in the instance ID, because the concept of roles is specific to our Oni tests. However, we can print out the **instance group name**, which in our case would very much equate to the role name.

The reason why we aren't doing this already is that the groups feature was introduced after the bulk of the runners code was written, and we never updated it to use more meaningful instance identification tactics, now that those were available.

I'll take care of this today, as it's a pain point for me and others.

**Comment by schomatis** [comment]
> concept of roles is specific to our Oni tests.

This is interesting, it would be useful if the Oni docs expand a bit on this (complementing the excellent Testground docs).

https://github.com/testground/testground/pull/1102 Solves the issue for me, thanks.
